### ISSUE TITLE
Add title field to time calc

### ISSUE THREAD

**Issue by friedger** [digitalkaoz/time-calc#49]
It would be nice to have a title as well.

**Comment by digitalkaoz** [comment]
hey, sorry for the long delay...you meant a title for the time-slot or a title for the whole PWA?

**Comment by friedger** [comment]
For the time slot. 

Am 8. August 2018 04:30:40 MESZ schrieb "Robert Schönthal" <notifications@github.com>:
>hey, sorry for the long delay...you meant a title for the time-slot or
>a title for the whole PWA?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/digitalkaoz/time-calc/issues/49#issuecomment-411263596

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
